//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibsonWeds.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_User()
        {
            this.db_Activity = new HashSet<db_Activity>();
            this.db_Registry = new HashSet<db_Registry>();
        }
    
        public long userID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string Cell { get; set; }
        public Nullable<bool> allowPlusOne { get; set; }
        public Nullable<bool> isPlusOne { get; set; }
        public Nullable<long> groupCoupleID { get; set; }
        public bool isGuest { get; set; }
        public Nullable<bool> isAdmin { get; set; }
        public Nullable<bool> hasRSVPd { get; set; }
        public bool isAttending { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Activity> db_Activity { get; set; }
        public virtual db_GroupCouple db_GroupCouple { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Registry> db_Registry { get; set; }
    }
}
