//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GibsonWeds.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GibsonWedsEntities : DbContext
    {
        public GibsonWedsEntities()
            : base("name=GibsonWedsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Activity> db_Activity { get; set; }
        public virtual DbSet<db_ActivityCategory> db_ActivityCategory { get; set; }
        public virtual DbSet<db_GroupCouple> db_GroupCouple { get; set; }
        public virtual DbSet<db_Registry> db_Registry { get; set; }
        public virtual DbSet<db_User> db_User { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
